// 관리자 BroadcastChannel 이벤트 표준

export const ADMIN_EVENTS = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  PAYMENT_UPDATED: 'PAYMENT_UPDATED',
  CALL_RECEIVED: 'CALL_RECEIVED',
};
